### ISSUE TITLE
Calling non-constant function

### ISSUE THREAD

**Issue by ToJen** [izetex/web3-eth#11] opened 2018-04-01 22:19 UTC
When I run this:
```ruby
        web3 = Web3::Eth::Rpc.new host: 'ropsten.infura.io/my_api_key', 
                                  port: 443,  
                                  connect_options: {
                                    open_timeout: 20,
                                    read_timeout: 140,
                                    use_ssl: true
                                  }
        # render html: web3.eth.blockNumber

        abi = [...myMethod...]
        contract = web3.eth.contract(abi)
        contractInstance = contract.at('...')
        
        result = contractInstance.myMethod(...)
        puts result
```
I get a `RuntimeError (Function myMethod is not constant: myMethod, requires to sign transaction)`. How do you sign a method call transaction?

**Comment by ToJen** [comment] 2018-04-03 11:50
@astudnev

**Comment by izetex** [comment] 2018-04-03 12:16
Is is a duplicate of https://github.com/izetex/web3-eth/issues/7 ?

**Comment by ToJen** [comment] 2018-04-03 12:26
I'm trying to execute a function not trying to send ether. Or do method calls have to be signed? I looked at #7 already.

**Comment by izetex** [comment] 2018-04-03 12:45
if call is not view or constant, it has to be signed

**Comment by ToJen** [comment] 2018-04-03 13:42
Yeah my functions aren't constant. But do I have to create a new key and sign for every function call?

**Comment by jlstr** [comment] 2018-06-16 23:17
Greetings,

Would you mind sharing the procedure to sign a Transaction in this precise Scenario? @ToJen How did you end up doing exactly... Is it possible for you to share a code example?

Thank you.

**Comment by 5hanth** [comment] 2018-07-09 04:48
running into same issue.. any ideas how to sign and use hex data with `transfer` method?

**Comment by jlstr** [comment] 2018-07-09 17:10
Hello @5hanth Please refer to issue #7, And look my replies. I have posted a brief example on how to do it.

Regards,

**Comment by 5hanth** [comment] 2018-07-10 04:20
Thanks @jlstr

apparently I end up using [ethereum.rb](https://github.com/EthWorks/ethereum.rb) gem  and

`client.personal_unlock_account(addr, pwd)`

`contract  = Ethereum::Contract.create(client: client, address: addr, name: token_name, abi: abi)`

`contract.transact.transfer(addr, value)`

**Closed as completed** 2019-11-20 21:58 UTC
